"""ReAct output parser - extracts Action/Final Answer from LLM output"""

import json
import re
from dataclasses import dataclass


@dataclass
class ReActAction:
    """Parsed tool call"""
    tool_name: str
    tool_input: dict


@dataclass
class ReActFinish:
    """Parsed final answer"""
    answer: str


def _strip_fabricated_observation(text: str) -> str:
    """
    Remove any Observation line the LLM wrote itself.
    Real observations are injected by the system, not generated by the LLM.
    """
    # Cut off everything from a self-written Observation onwards
    return re.split(r"\nObservation\s*:", text)[0].strip()


def parse_react_output(text: str) -> ReActAction | ReActFinish:
    """
    Parse LLM output to extract Action or Final Answer.
    Also strips any self-fabricated Observation lines.
    """
    # Strip fabricated observations before parsing
    text = _strip_fabricated_observation(text)

    # Check Final Answer
    final_match = re.search(r"Final Answer\s*:\s*(.+)", text, re.DOTALL)
    if final_match:
        return ReActFinish(answer=final_match.group(1).strip())

    # Extract Action and Action Input
    action_match = re.search(r"Action\s*:\s*(.+?)(?:\n|$)", text)
    input_match = re.search(r"Action Input\s*:\s*(.+?)(?:\n|$)", text, re.DOTALL)

    if not action_match:
        # No Action or Final Answer — treat Thought content as final answer
        thought_match = re.search(r"Thought\s*:\s*(.+)", text, re.DOTALL)
        if thought_match:
            return ReActFinish(answer=thought_match.group(1).strip())
        return ReActFinish(answer=text.strip())

    tool_name = action_match.group(1).strip()

    # Parse Action Input
    tool_input = {}
    if input_match:
        raw_input = input_match.group(1).strip()
        try:
            tool_input = json.loads(raw_input)
        except json.JSONDecodeError:
            tool_input = {"input": raw_input}

    return ReActAction(tool_name=tool_name, tool_input=tool_input)
